[package]
name = "hi-doc-jumprope"
version = "1.2.0"
authors = ["Joseph Gentle <me@josephg.com>", "Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2024"
description = "Simple, fast rope (fancy string) library built on top of Skiplists - hi-doc fork"
repository = "https://github.com/CertainLach/jumprope-rs"
license = "ISC OR Apache-2.0"
exclude = [
    "benchmark_data/*",
    ".github/**",
]

[workspace]
members = ["rope_benches", "crdt-testdata"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(doc_cfg)'] }

[features]
default = ["ddos_protection"]
# ddos_protection makes jumprope use a better RNG algorithm to avoid DOS
# attacks
ddos_protection = ["rand/std_rng", "rand/thread_rng"]
# wchar_conversion adds support for converting wchar positions (eg from JS or
# ObjC) into local unicode offsets.
wchar_conversion = []

# Line conversion adds support for editing using line/column offsets instead of character offsets.
line_conversion = []

# TODO: Remove me for 2.0 - the buffered feature is no longer needed.
buffered = []

[dependencies]
rand = { version = "0.9", default-features = false, features = ["small_rng"] }
str_indices = "0.4.4"

[dev-dependencies]
criterion = "0.8"
crdt-testdata = { path = "./crdt-testdata" }

[[bench]]
name = "benches"
harness = false

[profile.release]
lto = true
codegen-units = 1

[package.metadata.docs.rs]
features = ["wchar_conversion"]
